<?php

use Drupal\general\CustomEvent;

/**
 * Implements hook_theme().
 */
function general_theme() {
  return [
    'general_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
	'cache_tags_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

function general_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
	
	if($entity->bundle() == 'article') {
	  $dispatcher = \Drupal::service('event_dispatcher');
      $event = new CustomEvent($entity->label());
      $dispatcher->dispatch(CustomEvent::SUBMIT, $event);
	}	
}

function general_general_node_title(&$username) {
}


function general_general_node_title_alter(&$username) {
	$username = $username . ' - '. rand(10,100); 
}


